"""init

Revision ID: 083731a45343
Revises: 
Create Date: 2024-04-16 13:48:59.169424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083731a45343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ble_scan_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('devices_found', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('mac_addresses', sa.JSON(), nullable=True),
    sa.Column('presence', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ble_scan_data')
    # ### end Alembic commands ###
