"""userlog

Revision ID: 197fd2b9ccf9
Revises: 083731a45343
Create Date: 2024-04-16 13:53:28.335421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197fd2b9ccf9'
down_revision = '083731a45343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('presence', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_log')
    # ### end Alembic commands ###
