"""counter

Revision ID: a5f0fc4b0455
Revises: 197fd2b9ccf9
Create Date: 2024-04-20 17:04:55.678206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f0fc4b0455'
down_revision = '197fd2b9ccf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
